CI: Update and unify for cmake

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -81,52 +81,185 @@ jobs:
                 echo "::set-output name=should_skip::true"
             fi
 
+  build:
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+          include:
+          - os: ubuntu-22.04
+          - os: macos-12
+          - os: windows-2022
+      fail-fast: false
+    env: 
+      workingDir: build
+    defaults:
+      run:
+        shell: bash
+    steps:
+      - name: Checkout XKCP
+        uses: actions/checkout@v3
+      - name: Setup MS Build
+        if: runner.os == 'Windows'
+        uses: microsoft/setup-msbuild@v1.1
+      - name: Install Dependencies
+        run: |
+          case "${RUNNER_OS}" in
+              Linux)    echo "No requirement for Linux" ;;
+              macOS)    echo "No requirement for MacOS" ;;
+              Windows)  echo "No requirement for Windows" ;;
+              *)        echo "Do not recognise ${RUNNER_OS}." && exit 1 ;;
+          esac
+        env:
+          HOMEBREW_NO_ENV_HINTS: true
+      - name: Configure
+        run: |
+          mkdir $workingDir
+          cmake -B $workingDir -DBUILD_SHARED_LIBS=ON
+      - name: Make
+        run: |
+          make
+        working-directory: ${{ env.workingDir }}
+      - name: Validate Make
+        run: |
+          ls -la
+        working-directory: ${{ env.workingDir }}
+      - name: Upload Uncompressed Binaries
+        uses: actions/upload-artifact@v3
+        with:
+          name: XKCP-${{ runner.os }}-x86-NoUPX
+          path: |
+            $workingDir/**
+          if-no-files-found: error
+
+  compress:
+    name: Compress
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        include:
+        - os: ubuntu-22.04
+          filename: libXKCP.so
+        - os: windows-2022
+          filename: XKCP.DLL
+        arch: [ generic64, AVX, AVX2, AVX512, SSSE3, SSE42 ]
+      fail-fast: false
+    env: 
+      workingDir: build
+    defaults:
+      run:
+        shell: bash
+    steps:
+      - name: Download Artifacts
+        uses: actions/download-artifact@v3
+      - name: Compress Binaries
+        uses: svenstaro/upx-action@v2
+        with:
+          file: XKCP-${{ runner.os }}-x86-NoUPX/${{ matrix.arch }}/${{ matrix.filename }}
+          args: --best
+          strip: false
+      - name: Validate compression
+        run: |
+          ls -la
+        working-directory: ${{ env.workingDir }}
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: XKCP-${{ runner.os }}-x86-${{ matrix.arch }}-UPX
+          path: |
+            ${{ env.workingDir }}/${{ matrix.arch }}/${{ matrix.filename }}
+          if-no-files-found: error
+  
+  package:
+    name: Package libraries
+    runs-on: ubuntu-latest
+    env: 
+      workingDir: build
+    defaults:
+      run:
+        shell: bash
+    steps:
+      - name: Download Artifacts
+        uses: actions/download-artifact@v3
+      - name: Collect
+        run: |
+          mkdir collection
+          for platform in Linux macOS Windows
+          do
+            mkdir collection/${platform}
+            dir=collection/${platform}/x86
+            mkdir ${dir}
+            for arch in generic64 AVX AVX2 AVX512 SSSE3 SSE42
+            do
+              echo "Copying ${platform}/${arch}"
+              mkdir ${dir}/${arch}
+              cp XKCP-${platform}-x86-${arch}-UPX/* ${dir}/${arch}/
+            done
+          done
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: XKCP
+          path: |
+            collection/**
+          if-no-files-found: error
+
+
   build-win:
     runs-on: windows-latest
-    name: Build for Windows
+    name: Windows
     needs: skip_check
-    if: needs.skip_check.outputs.should_skip != 'true'
+    if: false && needs.skip_check.outputs.should_skip != 'true'
+    defaults:
+      run:
+        shell: msys2_shell.cmd -defterm -no-start -here -ucrt64 {0}
     steps:
     - uses: actions/checkout@v3
-    - name: Add msbuild to PATH
+    - name: Setup MS Build
       uses: microsoft/setup-msbuild@v1.1
-    - name: Add Path Msys64 Directory
+    - name: Add Msys64 to path
+      shell: pwsh
       run: |
         echo "c:\msys64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
     - name: Install msys2 dependencies
-      shell: msys2_shell.cmd -defterm -no-start -here -ucrt64 {0}
       run: |
         pacman -S --noconfirm ucrt64/mingw-w64-ucrt-x86_64-libxslt ucrt64/mingw-w64-ucrt-x86_64-make ucrt64/mingw-w64-ucrt-x86_64-gcc
         ln -s /ucrt64/bin/mingw32-make.exe /ucrt64/bin/make.exe
         echo GCC: $(which gcc)
         echo MAKE: $(which make)
         echo MSYSTEM: ${MSYSTEM}
-    - name: Build Generic64
-      shell: msys2_shell.cmd -defterm -no-start -here -ucrt64 {0}
+    - name: Get CPU features
+      id: cpu
+      run: |
+        echo "::set-output name=features::$(echo | gcc -march=native -dM -E - | tr -d '#define' | tr '\r\n' ' ')"
+    - name: Generic64
       run: |
         make generic64/libXKCP.so
+        make generic64/UnitTests && bin/generic64/UnitTests -a
       env:
         CFLAGS: -O3 -g0 -march=x86-64 -mtune=native
         ASMFLAGS: -march=x86-64 -mtune=native
-    - name: Build SSSE3
-      shell: msys2_shell.cmd -defterm -no-start -here -ucrt64 {0}
+    - name: SSE3
       run: |
-        make SSSE3/libXKCP.so
+        ./buildForFeature.sh $feature
       env:
+        feature: SSSE3
+        thisCPU: ${{ steps.cpu.outputs.features}}
         CFLAGS: -O3 -g0 -march=core2 -msse2 -mssse3 -mtune=native
         ASMFLAGS: -march=core2 -mtune=native
-    - name: Build AVX2
-      shell: msys2_shell.cmd -defterm -no-start -here -ucrt64 {0}
+    - name: AVX2
       run: |
-        make AVX2/libXKCP.so
+        ./buildForFeature.sh $feature
       env:
+        feature: AVX2
+        thisCPU: ${{ steps.cpu.outputs.features}}
         CFLAGS: -O3 -g0 -march=skylake -mtune=native
         ASMFLAGS: -march=skylake -mtune=native
-    - name: Build AVX512
-      shell: msys2_shell.cmd -defterm -no-start -here -ucrt64 {0}
+    - name: AVX512
       run: |
-        make AVX512/libXKCP.so
+        ./buildForFeature.sh $feature
       env:
+        feature: AVX512
+        thisCPU: ${{ steps.cpu.outputs.features}}
         CFLAGS: -O3 -g0 -march=skylake-avx512 -mtune=native
         ASMFLAGS: -march=skylake-avx512 -mtune=native
 
@@ -148,27 +281,50 @@ jobs:
           bin/artifacts/libXKCP-win.so.headers
 
   build-linux:
-    name: Build for Linux
+    name: Linux
     runs-on: ubuntu-latest
     needs: skip_check
-    if: needs.skip_check.outputs.should_skip != 'true'
+    if: false && needs.skip_check.outputs.should_skip != 'true'
     steps:
     - uses: actions/checkout@v3
     - name: Install dependencies
       run: |
         sudo apt-get update && sudo apt-get install xsltproc -y
-    - name: Build Generic64
+    - name: Get CPU features
+      id: cpu
       run: |
-        CFLAGS="-O3 -g0 -march=x86-64 -mtune=native" ASMFLAGS="-march=x86-64 -mtune=native" make generic64/libXKCP.so
-    - name: Build SSSE3
+        echo "::set-output name=features::$(echo | gcc -march=native -dM -E - | tr -d '#define' | tr '\n' ' ')"
+    - name: Generic64
       run: |
-        CFLAGS="-O3 -g0 -march=core2 -msse2 -mssse3 -mtune=native" ASMFLAGS="-march=core2 -mtune=native" make SSSE3/libXKCP.so
-    - name: Build AVX2
+        make generic64/libXKCP.so
+        make generic64/UnitTests && bin/generic64/UnitTests -a
+      env:
+        CFLAGS: -O3 -g0 -march=x86-64 -mtune=native
+        ASMFLAGS: -march=x86-64 -mtune=native
+    - name: SSSE3
       run: |
-        CFLAGS="-O3 -g0 -march=skylake -mtune=native" ASMFLAGS="-march=skylake -mtune=native" make AVX2/libXKCP.so
-    - name: Build AVX512
+        ./buildForFeature.sh $feature
+      env:
+        feature: SSSE3
+        thisCPU: ${{ steps.cpu.outputs.features}}
+        CFLAGS: -O3 -g0 -march=core2 -msse2 -mssse3 -mtune=native
+        ASMFLAGS: -march=core2 -mtune=native
+    - name: AVX2
       run: |
-        CFLAGS="-O3 -g0 -march=skylake-avx512 -mtune=native" ASMFLAGS="-march=skylake-avx512 -mtune=native" make AVX512/libXKCP.so
+        ./buildForFeature.sh $feature
+      env:
+        feature: AVX2
+        thisCPU: ${{ steps.cpu.outputs.features}}
+        CFLAGS: -O3 -g0 -march=skylake -mtune=native
+        ASMFLAGS: -march=skylake -mtune=native
+    - name: AVX512
+      run: |
+        ./buildForFeature.sh $feature
+      env:
+        feature: AVX512
+        thisCPU: ${{ steps.cpu.outputs.features}}
+        CFLAGS: -O3 -g0 -march=skylake-avx512 -mtune=native
+        ASMFLAGS: -march=skylake-avx512 -mtune=native
     - name: Rename artifacts
       run: |
           mkdir bin/artifacts
@@ -187,30 +343,62 @@ jobs:
           bin/artifacts/include
 
   build-osx:
-    name: Build for MacOS
+    name: MacOS
     runs-on: macos-latest
     needs: skip_check
-    if: needs.skip_check.outputs.should_skip != 'true'
+    if: false && needs.skip_check.outputs.should_skip != 'true'
     steps:
     - uses: actions/checkout@v3
     - name: Install dependencies
       run: |
         brew install libxslt
-    - name: Build for ARMv8A (M-series)
+    - name: Get CPU features
+      id: cpu
       run: |
-        CFLAGS="-target aarch64-apple-darwin -arch arm64 -O3 -g0 -march=armv8-a" ASMFLAGS="-march=armv8-a" make ARMv8A/libXKCP.dylib
-    - name: Build Generic x86_64
+        /usr/sbin/sysctl -n machdep.cpu.features machdep.cpu.leaf7_features
+        echo "::set-output name=features::$(echo | gcc -march=native -dM -E - | tr -d '#define' | tr '\n' ' ')"
+    - name: ARMv8A (M-series)
       run: |
-        CFLAGS="-target x86_64-apple-darwin -arch x86_64 -O3 -g0 -march=x86-64 -mtune=native" ASMFLAGS="-march=x86-64 -mtune=native" make generic64/libXKCP.dylib
-    - name: Build SSSE3
+        make ARMv8A/libXKCP.dylib
+        if [[ $(sysctl -n machdep.cpu.brand_string) =~ "Apple" ]]; then
+          make ARMv8A/UnitTests && bin/ARMv8A/UnitTests -a
+        else
+          echo "Intel CPU, can't test."
+        fi
+      env:
+        CFLAGS: -target aarch64-apple-darwin -arch arm64 -O3 -g0 -march=armv8-a
+        ASMFLAGS: -march=armv8-a
+    - name: Generic x86_64
       run: |
-        CFLAGS="-target x86_64-apple-darwin -arch x86_64 -O3 -g0 -march=core2 -msse2 -mssse3 -mtune=native" ASMFLAGS="-march=core2 -mtune=native" make SSSE3/libXKCP.dylib
-    - name: Build AVX2
+        make generic64/libXKCP.dylib
+        make generic64/UnitTests && bin/generic64/UnitTests -a
+      env:
+        CFLAGS: -O3 -g0 -target x86_64-apple-darwin -arch x86_64 -march=x86-64 -mtune=native
+        ASMFLAGS: -march=x86-64 -mtune=native
+    - name: SSE3
       run: |
-        CFLAGS="-target x86_64-apple-darwin -arch x86_64 -O3 -g0 -march=skylake -mtune=native" ASMFLAGS="-march=skylake -mtune=native" make AVX2/libXKCP.dylib
-    - name: Build AVX512
+        ./buildForFeature.sh $feature
+      env:
+        feature: SSSE3
+        thisCPU: ${{ steps.cpu.outputs.features}}
+        CFLAGS: -O3 -g0 -target x86_64-apple-darwin -arch x86_64 -march=core2 -msse2 -mssse3 -mtune=native
+        ASMFLAGS: -march=core2 -mtune=native
+    - name: AVX2
       run: |
-        CFLAGS="-target x86_64-apple-darwin -arch x86_64 -O3 -g0 -march=skylake-avx512 -mtune=native" ASMFLAGS="-march=skylake-avx512 -mtune=native" make AVX512/libXKCP.dylib
+        ./buildForFeature.sh $feature
+      env:
+        feature: AVX2
+        thisCPU: ${{ steps.cpu.outputs.features}}
+        CFLAGS: -O3 -g0 -target x86_64-apple-darwin -arch x86_64 -march=skylake -mtune=native
+        ASMFLAGS: -march=skylake -mtune=native
+    - name: AVX512
+      run: |
+        ./buildForFeature.sh $feature
+      env:
+        feature: AVX512
+        thisCPU: ${{ steps.cpu.outputs.features}}
+        CFLAGS: -O3 -g0 -target x86_64-apple-darwin -arch x86_64 -march=skylake-avx512 -mtune=native
+        ASMFLAGS: -march=skylake-avx512 -mtune=native
     - name: Rename and merge Generic64 and ARMv8A artifacts
       run: |
           mkdir bin/artifacts
